language: 
  - ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=default
  - DB=postgres
before_script:
  - bundle exec rake db:preprep
  - psql -c 'create database rsense_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
